### ISSUE TITLE
Drop do PHP < 5.5

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/pagseguro#10]
Algumas decisões de design foram limitadas em função de suportar o PHP 5.3+. 

Como temos o objetivo de seguir as boas práticas de desenvolvimento PHP, bora utilizar a última versão estável!

**Comment by fagundes** [comment]
@lcobucci Gostaria de ajudar a implementar o item restante. Qual seria sua ideia para isolar os módulos utilizando traits?

Eu ainda não conheço muito a lib em si. Mas dei uma olhada nas classes Serializers e Services que a utilizam, e entendi como funcionam. Porém, ainda não usei trait para aplicação real, então não tive nenhuma ideia para implementar isso.

**Comment by lcobucci** [comment]
@fagundes dê uma lida aqui: http://php.net/manual/en/language.oop5.traits.php

O lance das traits é apenas uma sugestão, o que acontece é que tem bastante duplicação no código. Se você tiver uma solução melhor pra isso, fique à vontade :smile:

**Comment by fagundes** [comment]
@lcobucci valeu a dica, mas o conceito em si de traits eu já entendi, só nunca usei mesmo. :wink: 

Pensei numa maneira genérica para resolver o serializer, mas seria utilizando reflexão. Dado um objeto a ser serializado, pegaria os metodos getters, o nome dos elementos (xml) seriam o nome dos atributos, para o valor teria três tratamentos a depender do tipo de dado: 
 
1. Para tipos básicos (string, int, float): só precisava formatar o valor;
- Para um objeto: seria serializar ele de forma recursiva (porque ele vai ter subelementos);
- Para uma collection (Ex. ItemCollection): não teria um valor, este seria um elemento com uma lista de objetos (cada item da coleção sendo inserido conforme o segundo caso).

De qualquer forma, com reflexão daria para resolver isso de maneira genérica, numa classe (ou trait). E as classes que precisam serializadas herdaria essa classe (ou melhor, usaria essa trait).

Um problema que vi para essa solução é a formatação dos dados, percebi que é feita substrings, cast para int, etc. E que isso varia de campo para campo, provavelmente conforme a especificação da API. Dessa forma uma classe (ou trait) genérica não resolveria isso sozinha, pq nao iria saber como formatar cada campo.

Não sei se fui claro, mas nada melhor que um código para se auto explicar, assim que eu poder eu faço uma implementação do que eu tentei explicar.

**Comment by lcobucci** [comment]
@fagundes dá pra utilizar algo como o http://jmsyst.com/libs/serializer it would be probably easier :smile:

**Comment by fagundes** [comment]
@lcobucci isso mesmo! Vai ficar beem mais fácil! O interessante é o uso das "anotações". Em breve vou fazer o PR, usando jms/serializer!

**Comment by lcobucci** [comment]
@fagundes Awesome man!
