### ISSUE TITLE
Aumentar cobertura de testes

### ISSUE THREAD

**Issue by lcobucci** [PHPSC/pagseguro#22]
- [x] PHPSC\PagSeguro\Items::Item
- [ ] PHPSC\PagSeguro\Purchases::Decoder
- [x] PHPSC\PagSeguro\Purchases::Details
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::CancellationRespons
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::Charge
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::ChargeBuilder
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::ChargeResponse
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::ChargeSerializer
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::Decoder
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::Locator
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::Subscription
- [x] PHPSC\PagSeguro\Purchases\Subscriptions::SubscriptionService
- [x] PHPSC\PagSeguro\Purchases\Transactions::Decoder
- [x] PHPSC\PagSeguro\Purchases\Transactions::Payment
- [x] PHPSC\PagSeguro\Purchases\Transactions::Transaction
- [x] PHPSC\PagSeguro\Requests::Serializer
- [x] PHPSC\PagSeguro\Requests\Checkout::Checkout
- [x] PHPSC\PagSeguro\Requests\Checkout::CheckoutSerializer
- [x] PHPSC\PagSeguro\Requests\Checkout::Order
- [x] PHPSC\PagSeguro\Requests\PreApprovals::ChargeType
- [x] PHPSC\PagSeguro\Requests\PreApprovals::Period
- [x] PHPSC\PagSeguro\Requests\PreApprovals::PreApproval
- [x] PHPSC\PagSeguro\Requests\PreApprovals::PreApprovalService
- [x] PHPSC\PagSeguro\Requests\PreApprovals::Request
- [x] PHPSC\PagSeguro\Requests\PreApprovals::RequestBuilder
- [x] PHPSC\PagSeguro\Requests\PreApprovals::RequestSerializer

**Comment by adelarcubs** [comment]
Vou criar alguns dos testes

**Comment by lcobucci** [comment]
Graças à ajuda do @moura137 e do @fagundes a gente está com uma cobertura de testes decente. Dessa forma vou fechar essa issue. Valeu galera!
