### ISSUE TITLE
Erro 401 ao fazer checkout.

### ISSUE THREAD

**Issue by hfingler** [PHPSC/pagseguro#23]
Estou construindo uma requisição e sempre que tento fazer o checkout aparece um erro 401 - Unauthorized no meu log.

 Já confirmei várias vezes o token e o email e eles estão corretos.
 O erro ocorre tanto no meu localhost quanto em produção.
 Estou tentando usar o sandbox.

 Código está assim:

    $credentials = new Credentials(
          'email_correto',
          'token_correto',
          new Sandbox()
      );

    try {
         $service = new CheckoutService($credentials);
         $checkout = $service->createCheckoutBuilder()
                           ->setCustomer(
                              new Customer($user->email,
                                 $user->name,
                                 new Phone(substr($user->phone, 0, 2), substr($user->phone, 2, strlen($user->phone) - 1)),
                                 new Address($ad->state, $ad->city, $ad->zip, $ad->area, $ad->address1, $ad->number, $ad->address2 ))
                           )
                           ->setReference($this->oid)
                           ->addItem(new Item(1, 'Televisão LED 500', 8999.99))
                           ->addItem(new Item(2, 'Video-game mega ultra blaster', 799.99))
                           ->getCheckout();

         $x = new CheckoutSerializer();
         \Log::info('serialize: ' . var_dump( $x->serialize($checkout) ));

         $response = $service->checkout($checkout);

         return $response->getRedirectionUrl();
      }
      catch (Exception $error) {
         return $error->getMessage();
      }

 Alguém tem idéia do que pode ser? O mesmo estava ocorrendo com a biblioteca PHP do pagseguro em meu localhost. Em produção não conseguir fazer funcionar por erros de namespace/class not found que até agora não sei porque ocorriam.

**Comment by lcobucci** [comment]
Você está utilizando o token de SANDBOX?

**Comment by hfingler** [comment]
São diferentes? Li toda a área logada do pagseguro e não achei nada sobre.
Onde eu consigo achá-lo? Muito obrigado.
Em 20/03/2015 18:55, "Luís Otávio Cobucci Oblonczyk" <
notifications@github.com> escreveu:
