### ISSUE TITLE
Consulta através do Código de Referência

### ISSUE THREAD

**Issue by MarlonEtiene** [PHPSC/pagseguro#35]
Olá,
Qual método/função devo utilizar para consultar uma transação através da referência definida por setReference?

Aproveitando, existe alguma limitação para a string que é passada para este método, tamanho ou qualquer outra?

Obrigado!

**Comment by lcobucci** [comment]
Olá @MarlonEtiene, desculpe a demora da resposta...

O pagseguro não possui consulta através da referência (veja as [consultas disponíveis aqui](https://pagseguro.uol.com.br/v2/guia-de-integracao/consultas.html)).

O ideal é utilizar o reference para integrar com o esquena de notificações (conforme explicado no README). O limite é encontrado [aqui](https://pagseguro.uol.com.br/v2/guia-de-integracao/api-de-pagamentos.html#v2-item-api-de-pagamentos-formato-xml).

**Comment by lcobucci** [comment]
Espero ter sanado suas dúvidas, qualquer coisa reabra a issue ;-)

**Comment by MarlonEtiene** [comment]
Opa, beleza!
Sanou a dúvida sim, obrigado!

**Comment by aneraojunior** [comment]
Poderiam me dizer como eu passo um código de referência na compra? Ainda não consegui. Grato

**Comment by aneraojunior** [comment]
Acabo de descobrir que na página dois foi explicado que basta usar ->setReference($referencia) abaixo do ->addItem. Desculpa pelo transtorno aí, pessoal.
