### ISSUE TITLE
Definir Tag Estável (Stable)

### ISSUE THREAD

**Issue by moura137** [PHPSC/pagseguro#37]
Ola @lcobucci 
Parabéns pelo projeto, porque a lib original do pagseguro não da para usar de forma simples.
Gostaria de saber se existe alguma data para definição da tag estavél.
Digo isso porque colocar em produção com o branch develop, não é nada recomendável.

**Comment by lcobucci** [comment]
Olá @moura137, vlw cara!

Realmente não é recomendável colocar um ```@dev``` no composer.
Eu to meio que sozinho neste projeto e não to conseguindo trabalhar muito em cima dele, por isso estou contando com a ajuda da galera pra fechar a #10 e #22 pra gente ter uma versão estável.

Infelizmente não temos data :disappointed:

**Comment by lcobucci** [comment]
@moura137 depois de 12893718927381798237 anos temos uma versão estável: https://github.com/PHPSC/pagseguro/releases/tag/1.0.0

Valeu pela força ;)
