### ISSUE TITLE
Erro ao utilizar integração

### ISSUE THREAD

**Issue by YanMagale** [PHPSC/pagseguro#40]
Boa tarde a todos. 

Estou usando a integração via HTML e estou recebendo o seguinte erro de retorno: invalid transactionCode value: notifications. Código do erro: 13003. Como trato este erro?

**Comment by lcobucci** [comment]
Olá @YanMagale, essa lib não é a oficial do pagseguro e focada apenas na integração via API.

Sugiro que você entre em contato com eles :smile:

**Comment by YanMagale** [comment]
Beleza @lcobucci , obrigado pelo feedback. Felizmente consegui resolver o erro, era uma configuração errada no .htacces do meu projeto..
