### ISSUE TITLE
Retorno de pagamento

### ISSUE THREAD

**Issue by kleverson** [PHPSC/pagseguro#43]
Começo parabenizando pelo excelente projeto, ficou excelente a sua biblioteca. 

Gostaria de tirar uma dúvida com você, como eu faço na biblioteca pra buscar o código da da transação do pagseguro, tem algum método pra ele??  

Tentei usar dessa maneira:

$credentials = new Credentials('<email>','<token>', new Sandbox());
$service =  new TransactionLocator($credentials);

$service->getByNotification($_POST['notificationCode']);

e não consegui buscar nada. Tem alguma outra forma??? É de outra forma que tem que ser feito??

**Comment by robsoncombr** [comment]
Eu estou tendo problemas aqui também. Acho que é algum bug.
No meu servidor, eu recebo do PagSeguro a notificação:
[2017-06-08 00:15:07] pro.DEBUG: array (
  'notificationCode' => 'CCD5B7-1F504F504F4A-7664B21F89B5-86B810',
  'notificationType' => 'transaction',
)
Então, quando chamo getByNotification do TransactionLocator ele chega ao PagSeguro, autentica mas retorna um erro:   #message: "[200] A HTTP error has occurred: "
Eu testei o acesso direto pelo browser funciona, também dei um dd($url) dentro da classe original e a url funciona quando acesso direto.
Alguma idéia?
Obrigado.

**Comment by cassiosantos** [comment]
Olá @kleverson . Agradeço muito pela sua interação. 

Infelizmente, como este issue não é atualizado desde 2016, estamos fechando.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
