### ISSUE TITLE
Problema de compatibilidade com Guzzle 6.0

### ISSUE THREAD

**Issue by ppeixoto** [PHPSC/pagseguro#44]
Parabéns pelo projeto, estou testando a Lib e encontrei um conflito para quem utiliza com Laravel 5.2 + Zendesk. Acredito que ainda esteja utilizando o Guzzle 5.3, que já foi deprecated.

**Comment by lcobucci** [comment]
Valeu @ppeixoto, sim precisamos atualizar isso, você poderia ajudar com um PR?

**Comment by ppeixoto** [comment]
Seria um prazer @lcobucci vou compatibilizar, testar e envio. Abs.

**Comment by 3run01** [comment]
Já foi compatibilizado @ppeixoto  ?

**Comment by lcobucci** [comment]
@ppeixoto @3run01 acabei de fazer o merge do #48, fechando essa issue.
