### ISSUE TITLE
Checkout Transparente

### ISSUE THREAD

**Issue by hugofcampos** [PHPSC/pagseguro#46]
Atualmente a API é compatível com o Checkout Transparente do Pagseguro?

**Comment by lcobucci** [comment]
Olá @hugofcampos, não implementamos esta funcionalidade, mas você pode enviar-nos um PR :smile:

**Comment by cassiosantos** [comment]
Olá @hugofcampos  . Agradeço muito seu contato.

Infelizmente, como este issue não é atualizado desde 2016, estamos fechando.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
