### ISSUE TITLE
setNotificationURL não funciona

### ISSUE THREAD

**Issue by gabrieldosanjospeixinho** [PHPSC/pagseguro#47]
Fiz a instalação via composer, na branch @dev porém não veio o commit da atualização de setNotificationUrl,
então decidi fazer com o git clone e excluir essa pasta do gitignore,
no entanto o mesmo não funciona quando chega no sandbox, o botão de enviar notificação local fica desabilitado.
Olhei no forum do pagseguro e é devido a falta do parametro notificationURL.

**Comment by gabrieldosanjospeixinho** [comment]
Deixa pra la... haha era erro no code... Mas mesmo assim como faço pra instalar via composer e pegar a versão do ultimo commit?

**Comment by sergiors** [comment]
@gabrieldosanjospeixinho vc pode dar uma olhada aqui https://getcomposer.org/doc/articles/aliases.md
