### ISSUE TITLE
Erro ao especificar o custo do ``Shipping``

### ISSUE THREAD

**Issue by pedrofs** [PHPSC/pagseguro#49]
Ao especificar o custo do `Shipping` o PagSeguro não reconhece o mesmo.

Exemplo:

```
$shipping = new Shipping($method, $address, $order->shipment_cost);
$builder->setShipping($shipping);
```

O XML gerado possui o dado `cost` da seguinte maneira:
`<cost>19,9</cost>`

Note a `vírgula` ao invés do `ponto`.

Olhando a classe `Shipping`, reparei que é feito um cast para float:
`$this->cost = (float) $cost;`

Eu substituí o cast por:
`$this->cost = str_replace(',', '.', strval($cost));`

Dessa maneira eu tenho um `ponto` ao invés da `vírgula` e assim o PagSeguro reconhece o valor fixo do frete.

PS.: Quando eu faço um cast e dou um echo é assim que aparece:
`(float) 19,9`

Talvez seja algo relacionada ao `locale`?

Alguma sugestão?

**Comment by lcobucci** [comment]
@pedrofs acabei de fazer merge da contribuição do @fagundes que pluga o JMS Serializer e agora todos os valores decimais são formatados corretamente.

Eu vou fechar essa issue aqui, mas se você ver que o problema ocorre novamente por favor reabra-a.
