### ISSUE TITLE
Url de redirecionamento dinâmica

### ISSUE THREAD

**Issue by ricardobarantini** [PHPSC/pagseguro#50]
Estou tentando enviar uma url dinâmica no redirectTo porém recebo erro 11007. Existe alguma limitação sobre urls dinâmicas nesse parâmetro?

Minha url recebe uma variável chamada id com um valor em md5. Por exemplo:
`http://dominio.com.br/sistema/?action=retorno&id=[md5aqui]`

No suporte do PagSeguro eles pedem para enviar um log do checkout para localizar o  erro, porém como estou utilizando essa biblioteca não tenho como enviar isso.

**Comment by cassiosantos** [comment]
Olá @ricardobarantini  . Agradecemos muito que você tenha entrado em contato.

Infelizmente, como este issue não é atualizado desde 2018, estamos fechando.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
