### ISSUE TITLE
trialPeriodDuration

### ISSUE THREAD

**Issue by marcelocamargosjr** [PHPSC/pagseguro#51]
Preciso aplicar em meu método para criar assinatura o "trialPeriodDuration" como fazer usando a biblioteca?

$request = $service->createRequestBuilder(false)
->setReference(Input::get('id'))
->setName('')
->setDetails('.')
->setPeriod(Period::YEARLY)
->setFinalDate($dateTimeCurrent->modify('+24 months'))
->setMaxTotalAmount(24 * $valor)
->setAmountPerPayment($valor)
 ->getRequest();

**Comment by lcobucci** [comment]
@marcelocamargosjr infelizmente eu não estou conseguindo manter essa lib. Você teria interesse em enviar um PR implementando sua necessidade?

**Comment by cassiosantos** [comment]
Olá @marcelocamargosjr  . Agradecemos muito o seu contato.

Infelizmente, como este issue não é atualizado desde 2017, estamos fechando.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
