### ISSUE TITLE
[Semantical Error] The annotation "@JMS\Serializer\Annotation\AccessType" in class PHPSC\PagSeguro\Requests\Checkout\Checkout does not exist, or could not be auto-loaded. in AnnotationException.php (line 54)

### ISSUE THREAD

**Issue by robsoncombr** [PHPSC/pagseguro#54]
Olá pessoal..
Após atualização para 1.0.1:

```sh
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)
  - Installing doctrine/annotations (v1.4.0): Downloading (100%)
  - Installing phpoption/phpoption (1.5.0): Downloading (100%)
  - Installing phpcollection/phpcollection (0.5.0): Downloading (100%)
  - Installing jms/parser-lib (1.0.0): Downloading (100%)
  - Installing jms/metadata (1.6.0): Downloading (100%)
  - Installing jms/serializer (1.7.1): Downloading (100%)
  - Updating guzzlehttp/guzzle (5.3.1 => 6.2.3): Downloading (100%)
  - Updating phpsc/pagseguro (dev-develop => 1.0.1): Downloading (100%)
  - Updating symfony/yaml (v3.3.1 => v3.3.2): Downloading (100%)
```

Eu agora recebo o seguinte erro quando tento criar um checkout (que funcionava antes):

```
(1/1) AnnotationException
[Semantical Error] The annotation "@JMS\Serializer\Annotation\AccessType" in class PHPSC\PagSeguro\Requests\Checkout\Checkout does not exist, or could not be auto-loaded.
in AnnotationException.php (line 54)
at AnnotationException::semanticalError('The annotation "@JMS\\Serializer\\Annotation\\AccessType" in class PHPSC\\PagSeguro\\Requests\\Checkout\\Checkout does not exist, or could not be auto-loaded.')
in DocParser.php (line 734)
```

Alguém saberia me ajuda?

Obrigado,

Robson

**Comment by lcobucci** [comment]
@robsoncombr a partir da versão estável estamos utilizando o JMS serializer pra criar as mensagens XML e ele é todo configurado via annotations. O que acontece é que seu projeto não está inicializando o autoloader de annotations, assim ele não encontra as classes necessárias.

Para resolver isso você precisa registrar o autoloader do composer no componente de annotations (https://github.com/PHPSC/pagseguro/blob/d094c8c6a3ad2c0c8a32d816a8d2724f4e60876a/bootstrap.php).

Normalmente isso é feito pelos frameworks que utilizam annotations possivelmente seu projeto não utiliza isso.

Você pode verificar se isto resolve seu problema, e caso resolver, nos enviar um PR pra atualizar a documentação com essa explicação (eu esqueci completamente de mencionar isso)?

**Comment by robsoncombr** [comment]
Olá @lcobucci obrigado pelo rápido retorno, novamente parabéns pelo projeto.
Eu havia encontrado e suspeitado do commit em que a serialização é introduzida..
Estou tentando imaginar como vou arrumar isso pelo Laravel 5.4.
Se alguém aí que estiver nos lendo souber, dá uma luz.
Aviso se eu conseguir resolver...

**Comment by lcobucci** [comment]
Você leu isso?

> Para resolver isso você precisa registrar o autoloader do composer no componente de annotations (https://github.com/PHPSC/pagseguro/blob/d094c8c6a3ad2c0c8a32d816a8d2724f4e60876a/bootstrap.php).

Essa é a única coisa que você deve fazer pra funcionar na versão estável. Se você não quer usar isso você pode usar as tags para navegar pelas versões antigas (https://github.com/PHPSC/pagseguro/releases), mas eu não recomendo isso.

Várias melhorias foram adicionar e erros corrigidos nesta versão estável e se fosse você simplesmente usaria a versão estável.

**Comment by robsoncombr** [comment]
Acho que não sei como fazer...

**Comment by lcobucci** [comment]
@robsoncombr você precisa basicamente copiar o código que está no link que eu te passei e adequá-lo ao seu projeto (diretórios e tudo mais), lembrando de colocar isso antes da execução de qualquer coisa.

Eu não uso o laravel, mas parece que é por aqui que vc colocaria esse código: https://github.com/laravel/laravel/blob/3acb7394502a87055f0d0447b9645cde5a9a85c0/bootstrap/autoload.php

**Comment by robsoncombr** [comment]
@lcobucci perfeito, funcionou.

Adicionei isso antes da execução da solicitação do Checkout e funcionou perfeitamente, cara você me ajudou muito. Estou aprendendo...

Futuramente, vou tentar descobrir uma forma de colocar isso no Framework ao invés de executar em toda a chamada, talvez seja mais apresentável.. mas de qualquer forma, funcionou.

Muito obrigado por sua atenção e ajuda.

**Comment by lcobucci** [comment]
@robsoncombr todos estamos aprendendo 😉 

Que bom que deu certo, seria realmente muito bacana você pudesse mandar um pull request atualizando a documentação dessa lib pra ajudar outras pessoas que possam estar passando pela mesma coisa.

**Comment by robsoncombr** [comment]
Uma observação...

Não consegui de forma alguma introduzir o código no bootstrap/autoload.php nativo do Laravel, estou chamando o AnnotationRegistry antes do Checkout por enquanto. Caso eu venha a resolver nativamente pleo Laravel, voltou a atualizar este para compartilhar com os outros.

Obrigado novamente.

**Comment by robledoleonardo** [comment]
Olá, @robsoncombr  e @lcobucci  consegui colocar no no bootstrap/autoload.php antes era assim:
```
define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so we do not have to manually load any of
| our application's PHP classes. It just feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';
```
Agora esta assim:

```
define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so we do not have to manually load any of
| our application's PHP classes. It just feels great to relax.
|
*/

$autoloader = require __DIR__.'/../vendor/autoload.php';

Doctrine\Common\Annotations\AnnotationRegistry::registerLoader([$autoloader, 'loadClass']);
```

**Comment by lucianorc** [comment]
Estou tendo essa dificuldade com o CodeIgniter! Alguém pode dar uma ajuda?

**Comment by sergiors** [comment]
@lucianorc vc tentou ja carregar o bootstrap.php q o @lcobucci citou?

**Comment by lucianorc** [comment]
Meu arquivo está igual mas aparece o mesmo erro.

**Comment by lucianorc** [comment]
Alguém tem mais alguma ideia?

**Comment by lcobucci** [comment]
@lucianorc sinceramente, a única questão possível é o fato de vc não ter o autoloader registrado pra carregar annotations. 

Você já rodou sua aplicação com um debugger com um breakpoint no `AnnotationRegistry::registerLoader()` pra ver se está sendo executado?

**Comment by gustavo-andrade** [comment]
Para quem ainda tiver problemas no Laravel 5.5, eu resolvi fazendo o seguinte, segui o conselho do Sérgio adicionando no bootstrap/app.php o seguinte código logo antes de retornar o $app:

`$autoloader = require __DIR__.'/../vendor/autoload.php';
Doctrine\Common\Annotations\AnnotationRegistry::registerLoader([$autoloader, 'loadClass']);
`

No meu PC começou a funcionar mas quando subi para o servidor continuou dando error, resolvi isso importando as seguintes partes do doctrine no composer.json e atualizando o composer:

`"require": {`
`...`  
`"doctrine/doctrine-bundle": "^1.6",`
      `  "doctrine/orm": "2.5.6",`
      `  "doctrine/annotations": "1.4.*",`
     `   "doctrine/dbal": "2.5.4",`  
`...`

**Comment by souljacker** [comment]
A solução do @gustavo-andrade , embora funcione, não me parece a mais recomendada. Para quem preferir uma solução que passe só pelo composer, esse pacote funcionou para mim

https://github.com/indigophp/doctrine-annotation-autoload

**Comment by keythdevsquad** [comment]
$ composer require indigophp/doctrine-annotation-autoload
$ composer dump-autoload

https://github.com/indigophp/doctrine-annotation-autoload

**Comment by MatheusHonorato** [comment]
valeu! ajudou demais
