### ISSUE TITLE
Semantical Error on Laravel

### ISSUE THREAD

**Issue by IgorDePaula** [PHPSC/pagseguro#59]
"[Semantical Error] The annotation "@JMS\Serializer\Annotation\AccessType" in class PHPSC\PagSeguro\Requests\Checkout\Checkout does not exist, or could not be auto-loaded.

**Comment by sergiors** [comment]
Oi @IgorDePaula na uma olhadinha em https://github.com/PHPSC/pagseguro/issues/54
Se resolve, por gentileza, fechar a issue.

**Comment by IgorDePaula** [comment]
O erro desapareceu, irei fechar.

Muito obrigado pela atençao.

**Comment by IgorDePaula** [comment]
Sua lib precisa ser atualizada, ao seguir seu conselho obtive o seguinte erro:

[Thu Jan 25 16:32:44 2018] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Doctrine\Common\Annotations\AnnotationRegistry::registerLoader() must be callable, array given, called in /home/igor/projetos/seederjobs/public/index.php on line 26 and defined in /home/igor/projetos/seederjobs/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:112
Stack trace:
#0 /home/igor/projetos/seederjobs/public/index.php(26): Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(Array)
#1 /home/igor/projetos/seederjobs/server.php(21): require_once('/home/igor/proj...')
#2 {main}
  thrown in /home/igor/projetos/seederjobs/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 112

**Comment by IgorDePaula** [comment]
Perdao, eu estava mosqueando.

**Comment by sergiors** [comment]
👊👏
