### ISSUE TITLE
Url de notificação dinâmica

### ISSUE THREAD

**Issue by MarlonEtiene** [PHPSC/pagseguro#60]
Olá,
Estou setando essa a url de notificação, porém, nos testes que fiz, quando vou no sandbox, mesmo eu mudando o status da transação, diz que não existe notificação

![image](https://user-images.githubusercontent.com/1870776/39010364-d77caac6-43e4-11e8-8260-1dc1effaf75a.png)

Mesmo pedindo para reenviar

![image](https://user-images.githubusercontent.com/1870776/39010475-23a3b0d4-43e5-11e8-8a90-809d03082c6f.png)

Porém eu havia verificado o xml gerado, e nele continha a url de notificação.
Seria isso um problema do Sandbox?

Desde já agradeço a atenção.

**Comment by MarlonEtiene** [comment]
@sergiors Ok, vou tentar fazer o teste no ambiente de produção.

Obrigado!

**Comment by MarlonEtiene** [comment]
Olá,
O tópico é um tanto antigo, mas só agora pude voltar nesse problema.
Descobri que a propriedade `setNotificationURL` não estava implementada na classe `CheckoutBuilder`.

Fiz essa implementação, e a notificação foi enviada com sucesso, mesmo no sandbox, funcionou perfeitamente.
Estarei fazendo uma PR para sua apreciação e se possível o merge.

Obrigado!

**Comment by cassiosantos** [comment]
Olá @MarlonEtiene . Como este issue não é atualizado desde janeiro, estamos fechando.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
