### ISSUE TITLE
Notificação de assinatura

### ISSUE THREAD

**Issue by Leocardoso94** [PHPSC/pagseguro#61]
Olá,

Pessoal como funciona para setar a url da notificação de assinatura?

Parabéns pela lib!

**Comment by mrprompt** [comment]
Acredito que sua resposta esteja em: `src/Requests/Checkout/Checkout.php` método `setNotificationURL`

**Comment by cassiosantos** [comment]
Olá @Leocardoso94 . Como este issue não é atualizado desde 2018, estamos fechando.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
