### ISSUE TITLE
Checkout de serviço

### ISSUE THREAD

**Issue by lmarttins** [PHPSC/pagseguro#62]
Oi !
Alguém sabe como setar o parâmetro "shippingAddressRequired=false" para o usar o checkout de serviço
ou alguma forma de não ser obrigatório os dados de endereço?

Valeu.

**Comment by mrprompt** [comment]
Acredito que se tu der uma olhada em `src/Requests/Checkout/Checkout.php`, você pode adicionar a propriedade `shippingAddressRequired` seguindo a documentação [aqui](https://devs.pagseguro.uol.com.br/docs/checkout-web-usando-a-tela-do-pagseguro), o padrão é true então caso adicione, seria legal manter isso para evitar qualquer problema futuro.

**Comment by cassiosantos** [comment]
Olá @lmarttins , como este issue não é atualizado desde 2018, estamos fechando. 

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.
