### ISSUE TITLE
Erro ao gerar cobrança manual

### ISSUE THREAD

**Issue by luanecomp** [PHPSC/pagseguro#65]
Olá pessoal,

Estou tentando enviar uma cobrança para uma assinatura manual que eu criei utilizando o exemplo na biblioteca e o pagseguro me retorna o seguinte erro: 

[Malformed request XML: {0}.] Malformed request XML: unexpected element (uri:"", local:"charge"). Expected elements are <{}address>,<{}item>,<{}payment>. in /home/[...]/vendor/phpsc/pagseguro/src/Client/PagSeguroException.php:16

Estou testando em ambiente Sandbox.

Verificando o xml que está sendo enviado, encontrei isso:

```
<charge>
  <preApprovalCode>464565465465465465465454654</preApprovalCode>
  <items>
    <item>
      <id>1</id>
      <description>Plano Mensal (30 dias). Quantidade de perfis: 1</description>
      <amount>80.00</amount>
      <quantity>1</quantity>
    </item>
  </items>
</charge>
```

Porém a documentação do pagseguro diposível aqui http://download.uol.com.br/pagseguro/docs/pagamento-recorrente.pdf informa que o padrão é:

```
<payment>
<items>
 <item>
 <id>0001</id>
<description>Seguro contra roubo - Notebook Prata</description>
 <amount>100.00</amount>
<quantity>1</quantity>
 </item>
</items>
 <reference>REF1234-1</reference>
<preApprovalCode>12E10BEF5E5EF94004313FB891C8E4CF</preApprovalCode>
 </payment> 
```

Alguem mais teve esse erro?

**Comment by lcobucci** [comment]
@luanecomp é bem possível que eles atualizaram a API desde esta implementação. Você poderia enviar um PR corrigindo as coisas?

**Comment by luanecomp** [comment]
Posso sim.

Percebi que ao alterar a linha @Serializer\XmlRoot("charge") para @Serializer\XmlRoot("payment") em PHPSC\PagSeguro\Purchases\Subscriptions\Charge faz com que a requisiçãos eja enviada corretamente para o pagseguro.

Irei fazer as alterações necessárias, incluindo mudança no nome das Classes e atributos, para trocar o Charge por Payment e mando um PR.

Até mais!

**Comment by cassiosantos** [comment]
Closed by #66
