### ISSUE TITLE
Variaveis de Ambiente

### ISSUE THREAD

**Issue by arikardnoir** [PHPSC/pagseguro#68]
Onde eu poderia setar as minhas credencias?

Acredito que seja uma questão de organização, mas gostaria de saber onde voces setam os valores das credenciais para que ele rode no Autoloader?  

Agradeceria bastante

**Comment by mrprompt** [comment]
Isso vai depender da sua aplicação, você pode configurar direto no seu arquivo `.env`, nas variáveis de ambiente do seu container e etc.

**Comment by arikardnoir** [comment]
[Semantical Error] The annotation "@JMS\Serializer\Annotation\AccessType" in class PHPSC\PagSeguro\Requests\Checkout\Checkout does not exist, or could not be auto-loaded.


Sabe me dizer o que é esse erro?

**Comment by mrprompt** [comment]
Dá uma olhada nessa thread: https://github.com/PHPSC/pagseguro/issues/54
