### ISSUE TITLE
pagseguro cancelando transação

### ISSUE THREAD

**Issue by nailsonIsrael** [PHPSC/pagseguro#70]
Galera, sei que o instuito aqui não é esse mas vou tentar uma ajuda aqui com vocês. 

Tenho uma aplicação minha Saas integrada com o pagseguro. A adesão do plano(Assinatura) acontece certinha, ele ativa, aguarda a transação validadora de 1,50 e mantém a adesão do cliente ativa. Mas na hora que vou fazer a transação do pagamento logo depois(Visto que não tem versão trial nos meus planos). O pagseguro simplesmente cancela os a transação e logo cancela a adesão que estava ativa. O pagseguro me joga de um setor para o outro e não consigo resolver meu problema. Alguém já passou por isso, sabe indicar um caminho? Os próprios atendentes alegam que minha integração e minha conta empresarial lá está ok.

Meus planos são simples e de forma manual pois minha aplicação controla a periodicidade para enviar os pagamentos pelo endpoint payment do pagseguro. 

Desde já agradeço o apoio de quem responder.

**Comment by cassiosantos** [comment]
Olá @nailsonIsrael , desculpe a falta de resposta.

Devido a falta de disponibilidade dos colaboradores, estamos descontinuando este projeto.
